import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./UI/Navbar";
import Footer from "./UI/Footer";
import Sidebar from "./UI/Sidebar";
import { ContextProvider } from "./Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <div className="min-h-screen w-full bg-[#101011] pt-32">
            <Sidebar />
            <Navbar />
            {children}
            <Footer />
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
